name: monomer
version: 1.3.0.0
github: fjvallarino/monomer
license: BSD3
author: Francisco Vallarino
maintainer: fjvallarino@gmail.com
copyright: 2018 Francisco Vallarino

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
synopsis: A GUI library for writing native Haskell applications.
category: GUI
description: |
  Monomer is an easy to use, cross platform, GUI library for writing native
  Haskell applications.

  It provides a framework similar to the Elm Architecture, allowing the creation
  of GUIs using an extensible set of widgets with pure Haskell.

  Please see the README on Github at <https://github.com/fjvallarino/monomer#readme>

default-extensions:
  - OverloadedStrings

dependencies:
  - async >= 2.1 && < 2.3
  - attoparsec >= 0.12 && < 0.15
  - base >= 4.11 && < 5
  - bytestring >= 0.10 && < 0.12
  - bytestring-to-vector >= 0.3 && < 0.4
  - containers >= 0.5.11 && < 0.7
  - data-default >= 0.5 && < 0.8
  - exceptions >= 0.10 && < 0.11
  - extra >= 1.6 && < 1.9
  - formatting >= 6.0 && < 8.0
  - http-client >= 0.6 && < 0.9
  - JuicyPixels >= 3.2.9 && < 3.5
  - lens >= 4.16 && < 6
  - mtl >= 2.1 && < 2.3
  - nanovg >= 0.8 && < 1.0
  - OpenGLRaw >= 3.3 && < 3.4
  - process >= 1.6 && < 1.7
  - sdl2 >= 2.5.0 && < 2.6
  - stm >= 2.5 && < 2.6
  - text >= 1.2 && < 2.1
  - text-show >= 3.7 && < 3.10
  - time >= 1.8 && < 1.16
  - transformers >= 0.5 && < 0.7
  - vector >= 0.12 && < 0.14
  - wreq >= 0.5.2 && < 0.6

library:
  source-dirs: src
  include-dirs: cbits
  install-includes:
    - fontmanager.h
  c-sources:
    - cbits/dpi.c
    - cbits/fontmanager.c
    - cbits/glew.c
  build-tools: c2hs
  cc-options:
    - -fPIC
  ghc-options:
    - -fwarn-incomplete-patterns
  when:
    - condition: os(windows)
      then:
        extra-libraries: glew32
      else:
        extra-libraries: GLEW

executables:
  todo:
    main: Main.hs
    source-dirs: examples/todo
    ghc-options:
      - -threaded
    dependencies:
      - monomer

  books:
    main: Main.hs
    source-dirs: examples/books
    ghc-options:
      - -threaded
    dependencies:
      - aeson >= 1.4 && < 2.3
      - monomer
      - wreq >= 0.5.2 && < 0.6

  ticker:
    main: Main.hs
    source-dirs: examples/ticker
    ghc-options:
      - -threaded
    dependencies:
      - aeson >= 1.4 && < 2.3
      - monomer
      - websockets >= 0.12 && < 0.13
      - wuss >= 1.1 && < 2.3

  generative:
    main: Main.hs
    source-dirs: examples/generative
    ghc-options:
      - -threaded
    dependencies:
      - monomer
      - random >= 1.1 && < 1.3

  opengl:
    main: Main.hs
    source-dirs: examples/opengl
    ghc-options:
      - -threaded
    dependencies:
      - monomer
      - random >= 1.1 && < 1.3

  tutorial:
    main: Main.hs
    source-dirs: examples/tutorial
    ghc-options:
      - -threaded
    dependencies:
      - monomer
      - random >= 1.1 && < 1.3

tests:
  monomer-test:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options:
      - -fwarn-incomplete-patterns
    dependencies:
      - directory >= 1.3 && < 1.4
      - monomer
      - hspec >= 2.4 && < 3.0
      - HUnit >= 1.6 && < 1.7
      - silently >= 1.2 && < 1.3
