name: "Build"
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
          extra_nix_config: |
            experimental-features = nix-command flakes ca-references
      - name: nix build
        run: |
          nix build
      - name: nix log
        if: ${{ always() }}
        run: |
          nix log &> ${{ matrix.os }}-monomer.log
      - name: upload ${{ matrix.os }}-monomer.log
        if: ${{ always() }}
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-monomer.log
          path: ${{ matrix.os }}-monomer.log
